apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsubuntu-app      # Deployment name used in Jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awsubuntu
  template:
    metadata:
      labels:
        app: awsubuntu
    spec:
      containers:
      - name: awsubuntu        # Container name used in Jenkins
        image: sirajahmad77/awsubuntu1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000